/* Generated configuration header file - do not edit */
#ifndef R_WIFI_ESP32_CONFIG_H
#define R_WIFI_ESP32_CONFIG_H

#define WIFI_CFG_SCI_CHANNEL			1

#define WIFI_CFG_SCI_INTERRUPT_LEVEL    14

#define WIFI_CFG_SCI_BAUDRATE           115200

#define WIFI_CFG_SCI_USE_FLOW_CONTROL		1

#define WIFI_CFG_RESET_PORT					4
#define WIFI_CFG_RESET_PIN					3

#define WIFI_CFG_CREATABLE_SOCKETS   		5

#define WIFI_CFG_SOCKETS_RECEIVE_BUFFER_SIZE  4096

#define WIFI_CFG_USE_CALLBACK_FUNCTION   0

#define WIFI_CFG_CALLBACK_FUNCTION_NAME   NULL


#endif /* #define R_WIFI_ESP32_CONFIG_H */
