/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 200m_95x91                                            *
* Dimensions:  95 * 91                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bm200m_95x91;

static GUI_CONST_STORAGE unsigned char _ac200m_95x91[] = {
  /* RLE: 090 Pixels @ 000,000 */ 90, 0xFF, 
  /* RLE: 005 Pixels @ 090,000 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 000,001 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 089,001 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 094,001 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 088,002 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 093,002 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 087,003 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 092,003 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 086,004 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 091,004 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 085,005 */ 5, 0x00, 
  /* RLE: 183 Pixels @ 090,005 */ 183, 0xFF, 
  /* ABS: 004 Pixels @ 083,007 */ 0, 4, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 090 Pixels @ 087,007 */ 90, 0xFF, 
  /* ABS: 006 Pixels @ 082,008 */ 0, 6, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 088 Pixels @ 088,008 */ 88, 0xFF, 
  /* ABS: 007 Pixels @ 081,009 */ 0, 7, 0x00, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 087 Pixels @ 088,009 */ 87, 0xFF, 
  /* ABS: 007 Pixels @ 080,010 */ 0, 7, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 092 Pixels @ 087,010 */ 92, 0xFF, 
  /* ABS: 002 Pixels @ 084,011 */ 0, 2, 0x00, 0x00, 
  /* RLE: 086 Pixels @ 086,011 */ 86, 0xFF, 
  /* RLE: 006 Pixels @ 077,012 */ 6, 0x00, 
  /* RLE: 088 Pixels @ 083,012 */ 88, 0xFF, 
  /* RLE: 001 Pixels @ 076,013 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 077,013 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 082,013 */ 1, 0x00, 
  /* RLE: 087 Pixels @ 083,013 */ 87, 0xFF, 
  /* RLE: 001 Pixels @ 075,014 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 076,014 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 081,014 */ 1, 0x00, 
  /* RLE: 089 Pixels @ 082,014 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 076,015 */ 5, 0x00, 
  /* RLE: 181 Pixels @ 081,015 */ 181, 0xFF, 
  /* RLE: 006 Pixels @ 072,017 */ 6, 0x00, 
  /* RLE: 088 Pixels @ 078,017 */ 88, 0xFF, 
  /* RLE: 001 Pixels @ 071,018 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 072,018 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 077,018 */ 1, 0x00, 
  /* RLE: 087 Pixels @ 078,018 */ 87, 0xFF, 
  /* RLE: 001 Pixels @ 070,019 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 071,019 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 076,019 */ 1, 0x00, 
  /* RLE: 089 Pixels @ 077,019 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 071,020 */ 5, 0x00, 
  /* RLE: 182 Pixels @ 076,020 */ 182, 0xFF, 
  /* RLE: 005 Pixels @ 068,022 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 073,022 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 067,023 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 072,023 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 066,024 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 071,024 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 065,025 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 070,025 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 064,026 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 069,026 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 063,027 */ 5, 0x00, 
  /* RLE: 371 Pixels @ 068,027 */ 254, 0xFF, 117, 0xFF, 
  /* RLE: 005 Pixels @ 059,031 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 064,031 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 058,032 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 063,032 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 057,033 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 062,033 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 056,034 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 061,034 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 055,035 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 060,035 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 054,036 */ 5, 0x00, 
  /* RLE: 183 Pixels @ 059,036 */ 183, 0xFF, 
  /* ABS: 004 Pixels @ 052,038 */ 0, 4, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 090 Pixels @ 056,038 */ 90, 0xFF, 
  /* ABS: 006 Pixels @ 051,039 */ 0, 6, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 088 Pixels @ 057,039 */ 88, 0xFF, 
  /* ABS: 007 Pixels @ 050,040 */ 0, 7, 0x00, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 087 Pixels @ 057,040 */ 87, 0xFF, 
  /* ABS: 007 Pixels @ 049,041 */ 0, 7, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 092 Pixels @ 056,041 */ 92, 0xFF, 
  /* ABS: 002 Pixels @ 053,042 */ 0, 2, 0x00, 0x00, 
  /* RLE: 086 Pixels @ 055,042 */ 86, 0xFF, 
  /* RLE: 006 Pixels @ 046,043 */ 6, 0x00, 
  /* RLE: 088 Pixels @ 052,043 */ 88, 0xFF, 
  /* RLE: 001 Pixels @ 045,044 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 046,044 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 051,044 */ 1, 0x00, 
  /* RLE: 087 Pixels @ 052,044 */ 87, 0xFF, 
  /* RLE: 001 Pixels @ 044,045 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 045,045 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 050,045 */ 1, 0x00, 
  /* RLE: 089 Pixels @ 051,045 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 045,046 */ 5, 0x00, 
  /* RLE: 181 Pixels @ 050,046 */ 181, 0xFF, 
  /* RLE: 006 Pixels @ 041,048 */ 6, 0x00, 
  /* RLE: 088 Pixels @ 047,048 */ 88, 0xFF, 
  /* RLE: 001 Pixels @ 040,049 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 041,049 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 046,049 */ 1, 0x00, 
  /* RLE: 087 Pixels @ 047,049 */ 87, 0xFF, 
  /* RLE: 001 Pixels @ 039,050 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 040,050 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 045,050 */ 1, 0x00, 
  /* RLE: 089 Pixels @ 046,050 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 040,051 */ 5, 0x00, 
  /* RLE: 182 Pixels @ 045,051 */ 182, 0xFF, 
  /* RLE: 005 Pixels @ 037,053 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 042,053 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 036,054 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 041,054 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 035,055 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 040,055 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 034,056 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 039,056 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 033,057 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 038,057 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 032,058 */ 5, 0x00, 
  /* RLE: 371 Pixels @ 037,058 */ 254, 0xFF, 117, 0xFF, 
  /* RLE: 005 Pixels @ 028,062 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 033,062 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 027,063 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 032,063 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 026,064 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 031,064 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 025,065 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 030,065 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 024,066 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 029,066 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 023,067 */ 5, 0x00, 
  /* RLE: 183 Pixels @ 028,067 */ 183, 0xFF, 
  /* ABS: 004 Pixels @ 021,069 */ 0, 4, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 090 Pixels @ 025,069 */ 90, 0xFF, 
  /* ABS: 006 Pixels @ 020,070 */ 0, 6, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 088 Pixels @ 026,070 */ 88, 0xFF, 
  /* ABS: 007 Pixels @ 019,071 */ 0, 7, 0x00, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 087 Pixels @ 026,071 */ 87, 0xFF, 
  /* ABS: 007 Pixels @ 018,072 */ 0, 7, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 092 Pixels @ 025,072 */ 92, 0xFF, 
  /* ABS: 002 Pixels @ 022,073 */ 0, 2, 0x00, 0x00, 
  /* RLE: 086 Pixels @ 024,073 */ 86, 0xFF, 
  /* RLE: 006 Pixels @ 015,074 */ 6, 0x00, 
  /* RLE: 088 Pixels @ 021,074 */ 88, 0xFF, 
  /* RLE: 001 Pixels @ 014,075 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 015,075 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 020,075 */ 1, 0x00, 
  /* RLE: 087 Pixels @ 021,075 */ 87, 0xFF, 
  /* RLE: 001 Pixels @ 013,076 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 014,076 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 019,076 */ 1, 0x00, 
  /* RLE: 089 Pixels @ 020,076 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 014,077 */ 5, 0x00, 
  /* RLE: 181 Pixels @ 019,077 */ 181, 0xFF, 
  /* RLE: 006 Pixels @ 010,079 */ 6, 0x00, 
  /* RLE: 088 Pixels @ 016,079 */ 88, 0xFF, 
  /* RLE: 001 Pixels @ 009,080 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 010,080 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,080 */ 1, 0x00, 
  /* RLE: 087 Pixels @ 016,080 */ 87, 0xFF, 
  /* RLE: 001 Pixels @ 008,081 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 009,081 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 014,081 */ 1, 0x00, 
  /* RLE: 089 Pixels @ 015,081 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 009,082 */ 5, 0x00, 
  /* RLE: 182 Pixels @ 014,082 */ 182, 0xFF, 
  /* RLE: 005 Pixels @ 006,084 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 011,084 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 005,085 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 010,085 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 004,086 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 009,086 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 003,087 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 008,087 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 002,088 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 007,088 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 001,089 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 006,089 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 000,090 */ 5, 0x00, 
  /* RLE: 090 Pixels @ 005,090 */ 90, 0xFF, 
  0
};  // 436 bytes for 8645 pixels

GUI_CONST_STORAGE GUI_BITMAP bm200m_95x91 = {
  95, // xSize
  91, // ySize
  95, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_ac200m_95x91,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
