/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: startend_95x91                                        *
* Dimensions:  95 * 91                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmstartend_95x91;

static GUI_CONST_STORAGE unsigned char _acstartend_95x91[] = {
  /* RLE: 090 Pixels @ 000,000 */ 90, 0xFF, 
  /* RLE: 005 Pixels @ 090,000 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 000,001 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 089,001 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 094,001 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 088,002 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 093,002 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 087,003 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 092,003 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 086,004 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 091,004 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 085,005 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 090,005 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 084,006 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 089,006 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 083,007 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 088,007 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 082,008 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 087,008 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 081,009 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 086,009 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 080,010 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 085,010 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 079,011 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 084,011 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 078,012 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 083,012 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 077,013 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 082,013 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 076,014 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 081,014 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 075,015 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 080,015 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 074,016 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 079,016 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 073,017 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 078,017 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 072,018 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 077,018 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 071,019 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 076,019 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 070,020 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 075,020 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 069,021 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 074,021 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 068,022 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 073,022 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 067,023 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 072,023 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 066,024 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 071,024 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 065,025 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 070,025 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 064,026 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 069,026 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 063,027 */ 5, 0x00, 
  /* RLE: 371 Pixels @ 068,027 */ 254, 0xFF, 117, 0xFF, 
  /* RLE: 005 Pixels @ 059,031 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 064,031 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 058,032 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 063,032 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 057,033 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 062,033 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 056,034 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 061,034 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 055,035 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 060,035 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 054,036 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 059,036 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 053,037 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 058,037 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 052,038 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 057,038 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 051,039 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 056,039 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 050,040 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 055,040 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 049,041 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 054,041 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 048,042 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 053,042 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 047,043 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 052,043 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 046,044 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 051,044 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 045,045 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 050,045 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 044,046 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 049,046 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 043,047 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 048,047 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 042,048 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 047,048 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 041,049 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 046,049 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 040,050 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 045,050 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 039,051 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 044,051 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 038,052 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 043,052 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 037,053 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 042,053 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 036,054 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 041,054 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 035,055 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 040,055 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 034,056 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 039,056 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 033,057 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 038,057 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 032,058 */ 5, 0x00, 
  /* RLE: 371 Pixels @ 037,058 */ 254, 0xFF, 117, 0xFF, 
  /* RLE: 005 Pixels @ 028,062 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 033,062 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 027,063 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 032,063 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 026,064 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 031,064 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 025,065 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 030,065 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 024,066 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 029,066 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 023,067 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 028,067 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 022,068 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 027,068 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 021,069 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 026,069 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 020,070 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 025,070 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 019,071 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 024,071 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 018,072 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 023,072 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 017,073 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 022,073 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 016,074 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 021,074 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 015,075 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 020,075 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 014,076 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 019,076 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 013,077 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 018,077 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 012,078 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 017,078 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 011,079 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 016,079 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 010,080 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 015,080 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 009,081 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 014,081 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 008,082 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 013,082 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 007,083 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 012,083 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 006,084 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 011,084 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 005,085 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 010,085 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 004,086 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 009,086 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 003,087 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 008,087 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 002,088 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 007,088 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 001,089 */ 5, 0x00, 
  /* RLE: 089 Pixels @ 006,089 */ 89, 0xFF, 
  /* RLE: 005 Pixels @ 000,090 */ 5, 0x00, 
  /* RLE: 090 Pixels @ 005,090 */ 90, 0xFF, 
  0
};  // 346 bytes for 8645 pixels

GUI_CONST_STORAGE GUI_BITMAP bmstartend_95x91 = {
  95, // xSize
  91, // ySize
  95, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acstartend_95x91,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
