/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.14                          *
*        Compiled Jun  2 2020, 15:49:31                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include <string.h>
#include "platform.h"
#include "r_flash_rx_if.h"
#include "r_tfat_lib.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_0   (GUI_ID_USER + 0x02)
#define ID_LISTBOX_0   (GUI_ID_USER + 0x03)
#define ID_TEXT_1   (GUI_ID_USER + 0x04)
#define ID_MULTIEDIT_0   (GUI_ID_USER + 0x05)
#define ID_TEXT_2   (GUI_ID_USER + 0x06)
#define ID_TEXT_3   (GUI_ID_USER + 0x07)
#define ID_BUTTON_1   (GUI_ID_USER + 0x08)
#define ID_BUTTON_2   (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
char selected_file_name2[256+1];
static const char reboot_string2[] = "Reboot";
char buff2[350];
char text2[13];
TEXT_Handle hText2;
FATFS fatfs2;
FILINFO filinfo2;
DIR dir2;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "D2AudioDemo", ID_WINDOW_0, 0, 21, 480, 228, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "D2 Audio Record and Play", ID_TEXT_0, 6, 0, 158, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "STOP", ID_BUTTON_0, 396, 201, 80, 20, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 7, 33, 129, 162, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "File List", ID_TEXT_1, 7, 18, 105, 20, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 142, 33, 334, 162, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "File Size", ID_TEXT_2, 8, 204, 51, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_3, 52, 204, 84, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PLAY", ID_BUTTON_1, 312, 201, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "RECORD", ID_BUTTON_2, 228, 201, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern void bank_swap_with_software_reset(void);
extern void software_reset(void);
extern void firmware_update_request(char *string);
extern bool is_firmupdating(void);
extern void SetSwbankchangeRebootBotton(void);
extern void firmware_update_request(char *string);
extern void d2audio_play_start(void);
extern void d2audio_play_stop(void);
extern void d2audio_record_start(void);
extern void d2audio_record_stop(void);

WM_HWIN hWinD2AudioRecordAndPlayWindow;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN hWin;
  int select_id;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'D2AudioDemo'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "Item 0");
    LISTBOX_AddString(hItem, "Item 1");
    LISTBOX_AddString(hItem, "Item 2");
    // USER START (Optionally insert additional code for further widget initialization)
    hText2 = TEXT_CreateEx(52, 204, 84, 20, pMsg->hWin, WM_CF_SHOW, TEXT_CF_LEFT, ID_TEXT_3, text2);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'STOP'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        d2audio_play_stop();
        d2audio_record_stop();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'PLAY'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        d2audio_play_start();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'RECORD'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        d2audio_record_start();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateD2AudioDemo
*/
WM_HWIN CreateD2AudioDemo(void);
WM_HWIN CreateD2AudioDemo(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
