/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.50                          *
*        Compiled Jun 11 2019, 16:51:25                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include <string.h>
#include "platform.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_EDIT_0     (GUI_ID_USER + 0x02)
#define ID_EDIT_1     (GUI_ID_USER + 0x03)
#define ID_MULTIEDIT_0     (GUI_ID_USER + 0x04)
#define ID_BUTTON_0     (GUI_ID_USER + 0x05)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x06)
#define ID_MULTIEDIT_1     (GUI_ID_USER + 0x07)
#define ID_MULTIEDIT_2     (GUI_ID_USER + 0x08)
#define ID_MULTIEDIT_3     (GUI_ID_USER + 0x09)
#define ID_BUTTON_1     (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
char selected_file_name[256+1];
static const char reboot_string[] = "Reboot";
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SecureUpdateWindow", ID_WINDOW_0, 5, 23, 467, 228, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Secure Update Demo", ID_TEXT_0, 21, 6, 140, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 15, 195, 150, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 15, 117, 150, 20, 0, 0x64, 0 },
  { MULTIEDIT_CreateIndirect, "LogEdit", ID_MULTIEDIT_0, 268, 30, 185, 185, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 182, 172, 80, 20, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 179, 30, 86, 138, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_1, 15, 136, 150, 60, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_2, 15, 58, 150, 60, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_3, 15, 30, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "swap", ID_BUTTON_1, 183, 197, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern WM_HWIN hWinSecureUpdatewindow;
extern void firmware_update_request(char *string);
extern void bank_swap(void);
extern void SetSwbankchangeRebootBotton(void);

void firmware_update_writing_color(U32 id, U8 num);
void firmware_update_temporary_area_string(U32 prog, U32 kilobyte);
void firmware_update_log_string(char *pstring);

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  int select_id;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'SecureUpdateWindow'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "Secure Boot");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "Secure Boot (mirror)");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'LogEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetText(hItem, "");
    MULTIEDIT_SetFont(hItem, GUI_FONT_8_1);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "update");
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_SetFont(hItem, GUI_FONT_13_1);
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    LISTBOX_AddString(hItem, "");
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_1);
    MULTIEDIT_SetText(hItem, "Firmware Area");
    MULTIEDIT_SetFont(hItem, GUI_FONT_13_1);
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_2);
    MULTIEDIT_SetText(hItem, "Temporary");
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_3);
    MULTIEDIT_SetText(hItem, "Hash Value(Firmware)");
    MULTIEDIT_SetFont(hItem, GUI_FONT_13_1);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetReadOnly(hItem, 1);
	MULTIEDIT_SetAutoScrollV(hItem, 1);
	MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, GUI_MAKE_COLOR(0x00FFFFFF));
    MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY, GUI_MAKE_COLOR(0x00000000));

    /* Secureboot */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FFFF00));

    /* Secureboot(mirror) */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetBkColor  (hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FFFF00));

    /* Firmware Area  */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_1);
    MULTIEDIT_SetTextAlign(hItem, GUI_TA_HCENTER);
    MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, GUI_MAKE_COLOR(0x00000000));
    MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY, GUI_MAKE_COLOR(0x00FFFFFF));
    MULTIEDIT_SetReadOnly(hItem, 1);

    /* Temporary Area  */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_2);
    MULTIEDIT_SetTextAlign(hItem, GUI_TA_HCENTER);
    MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, GUI_MAKE_COLOR(0x00000000));
    MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY, GUI_MAKE_COLOR(0x00FFFFFF));
    MULTIEDIT_SetReadOnly(hItem, 1);

    /* listbox  */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetTextColor(hItem,LISTBOX_CI_SEL,GUI_MAKE_COLOR(0x000000));


    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'LogEdit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
      {
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);

    	  char text[16];
    	  BUTTON_GetText(hItem, text, sizeof(text)-1);
    	  if(0 == strcmp(text, reboot_string))
    	  {
    		  SetSwbankchangeRebootBotton();
    	  }
    	  else
    	  {
			  WM_HWIN hItem;
			  WM_HWIN hWin;

			  hWin = hWinSecureUpdatewindow;
			  hItem = WM_GetDialogItem(hWin, ID_LISTBOX_0);

			  select_id = LISTBOX_GetSel(hItem);
			  if(select_id == -1)
			  {
				  return;
			  }
			  LISTBOX_GetItemText(hItem, select_id, selected_file_name, 256);
			  //firmware_update_request(selected_file_name);
			  firmware_update_log_string("start firmware update.\r\n");
    	  }
      }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_1: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_2: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_3: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'swap'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		while(1); /* should not reach this sequence */
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSecureUpdateWindow
*/
WM_HWIN CreateSecureUpdateWindow(void);
WM_HWIN CreateSecureUpdateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void firmware_update_log_string(char *pstring)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin;

	  hWin = hWinSecureUpdatewindow;
	  hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_0);
	  MULTIEDIT_AddText(hItem, pstring);
	  MULTIEDIT_SetCursorOffset(hItem, MULTIEDIT_GetTextSize(hItem));
}

void firmware_update_list_add(char *pstring)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin;

	  hWin = hWinSecureUpdatewindow;
	  hItem = WM_GetDialogItem(hWin, ID_LISTBOX_0);

	  LISTBOX_AddString(hItem, pstring);
}

void firmware_update_list_clear(void)
{
	U32 list_num;
	I32 i;
	  WM_HWIN hItem;
	  WM_HWIN hWin;

	  hWin = hWinSecureUpdatewindow;
	  hItem = WM_GetDialogItem(hWin, ID_LISTBOX_0);

	  list_num = LISTBOX_GetNumItems(hItem);
	  for(i = list_num-1;i>=0;i--)
	  {
		  LISTBOX_DeleteItem(hItem, i);
	  }
}

void firmware_update_writing_color(U32 id, U8 num)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin;
	  U32 color;
	  hWin = hWinSecureUpdatewindow;
	  switch(id)
	  {
	  case 3:
		  hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_2);
		  break;
	  case 4:
		  hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_3);
		  break;
	  }
	color = ((U32)num << 16) | (U32)0xffff;
	MULTIEDIT_SetBkColor  (hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(color));
    MULTIEDIT_SetText  (hItem, "Writing...");

}

void firmware_update_writing_color_clear(void)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	hWin = hWinSecureUpdatewindow;
	hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_2);
	MULTIEDIT_SetBkColor  (hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FFFFFF));
	MULTIEDIT_SetText  (hItem, "");
	hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_3);
	MULTIEDIT_SetBkColor  (hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FFFFFF));

}

#define MOVE_WINDOW_COUNT 78

#define AREA_CURVE_X 10
#define AREA_CURVE_Y 3
#define AREA_CURVE_DELAY 3

void firmware_update_editor_move(void)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin;
	  int xsize,ysize,xpos,ypos;

	  int cnt = 0;
	  while(cnt < MOVE_WINDOW_COUNT)
	  {
		  /* 上から下へ降りる方 */
		  /* Temporary Area */
		hWin = hWinSecureUpdatewindow;
		hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_2);
		xpos = WM_GetWindowOrgX(hItem);
		ypos = WM_GetWindowOrgY(hItem);
		xsize = WM_GetWindowSizeX(hItem);
		ysize = WM_GetWindowSizeY(hItem);
		if(cnt < AREA_CURVE_X)
		{
			xpos+=AREA_CURVE_Y;
		}
		else if(cnt >= (MOVE_WINDOW_COUNT - AREA_CURVE_X))
		{
			xpos-=AREA_CURVE_Y;
		}
		ypos++;
		WM_SetWindowPos(hItem, xpos, ypos, xsize, ysize);

		  /* Secureboot(mirror) */
		hItem = WM_GetDialogItem(hWin, ID_EDIT_1);
		xpos = WM_GetWindowOrgX(hItem);
		ypos = WM_GetWindowOrgY(hItem);
		xsize = WM_GetWindowSizeX(hItem);
		ysize = WM_GetWindowSizeY(hItem);
		if(cnt < AREA_CURVE_X)
		{
			xpos+=AREA_CURVE_Y;
		}
		else if(cnt >= (MOVE_WINDOW_COUNT - AREA_CURVE_X))
		{
			xpos-=AREA_CURVE_Y;
		}
		ypos++;
		WM_SetWindowPos(hItem, xpos, ypos, xsize, ysize);

		/* 下から上へ上る方 */
		  /* Frimware Area */
		hWin = hWinSecureUpdatewindow;
		hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_1);
		xpos = WM_GetWindowOrgX(hItem);
		ypos = WM_GetWindowOrgY(hItem);
		xsize = WM_GetWindowSizeX(hItem);
		ysize = WM_GetWindowSizeY(hItem);
		if(cnt < AREA_CURVE_X)
		{
			xpos-=AREA_CURVE_Y;
		}
		else if(cnt >= (MOVE_WINDOW_COUNT - AREA_CURVE_X))
		{
			xpos+=AREA_CURVE_Y;
		}
		ypos--;
		WM_SetWindowPos(hItem, xpos, ypos, xsize, ysize);

		  /* Secureboot(mirror) */
		hItem = WM_GetDialogItem(hWin, ID_EDIT_0);
		xpos = WM_GetWindowOrgX(hItem);
		ypos = WM_GetWindowOrgY(hItem);
		xsize = WM_GetWindowSizeX(hItem);
		ysize = WM_GetWindowSizeY(hItem);
		if(cnt < AREA_CURVE_X)
		{
			xpos-=AREA_CURVE_Y;
		}
		else if(cnt >= (MOVE_WINDOW_COUNT - AREA_CURVE_X))
		{
			xpos+=AREA_CURVE_Y;
		}
		ypos--;
		WM_SetWindowPos(hItem, xpos, ypos, xsize, ysize);
		GUI_Delay(AREA_CURVE_DELAY);
        cnt++;
	  }


}

void firmware_update_temporary_area_string(U32 prog, U32 kilobyte)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin;
	  U8 buff[256+40];
	sprintf(buff, "%s\r\n%d\% (%3dKB/960KB)",selected_file_name, prog, kilobyte);
	  /* Temporary Area */
	hWin = hWinSecureUpdatewindow;
	hItem = WM_GetDialogItem(hWin, ID_MULTIEDIT_2);
	MULTIEDIT_SetText(hItem, buff);

}

void firmware_update_ok_after_message(void)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin;
	  U8 buff[350];
		sprintf(buff,
		    "\r\nNew Firmware install succeeded.\r\n\r\n");
		firmware_update_log_string(buff);
		GUI_Delay(1);
		sprintf(buff,
			" After \"Reboot\" button pushed,\r\n"
			" the followings will be executed.\r\n"
            " 1. Swap the Flash memory bank.\r\n"
			"    (Firmware and Temporary area)\r\n"
			" 2. Reboot the MCU.\r\n"
			" 3. Re-start secure boot to\r\n"
			"    verify new firmware.\r\n"
		    " 4. Jump to new firmware.\r\n");

		  /* Temporary Area */
		firmware_update_log_string(buff);
		hWin = hWinSecureUpdatewindow;
		hItem = WM_GetDialogItem(hWin, ID_BUTTON_0);
		BUTTON_SetText(hItem, reboot_string);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		GUI_Delay(1);
}

void firmware_update_ng_after_message(void)
{
	  char buff[350];
		sprintf(buff,
		    "\r\nNew Firmware install failed.\r\n\r\n");
		firmware_update_log_string(buff);
		GUI_Delay(1);
}
// USER END

/*************************** End of file ****************************/
