/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.48                       *
*        Compiled Jun 13 2018, 10:49:54                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_48.c                                             *
* Font:        Boxy Bold                                             *
* Height:      48                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  48                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x52 (82)                                     *
* Character enabled:   0x43 (67)                                     *
* Character enabled:   0x48 (72)                                     *
* Character enabled:   0x45 (69)                                     *
* Character enabled:   0x59 (89)                                     *
* Character enabled:   0x20 (32)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_48;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0020[  6] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0041[430] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,XXXXXX__,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,________,XXXXXX__,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,XXXXXX__,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____XX,XXXXXXXX,______XX,XXXXXXXX,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,XXXXX___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0043[430] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,XXXXX___,
  X_____X_,_______X,________,________,X_______,
  X_____X_,_______X,________,________,X_______,
  X_____X_,_______X,________,________,X_______,
  X_____X_,_______X,________,________,XXXXX___,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,________,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0045[430] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,___XXXXX,________,
  _XXXXX__,________,________,___XXXXX,________,
  _XXXXX__,________,________,___XXXXX,________,
  _XXXXX__,________,________,___XXXXX,________,
  _XXXXX__,________,________,___XXXXX,________,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,________,XXXXXXXX,XXX_____,XXXXX___,
  X_____X_,________,________,__X_____,X_______,
  X_____X_,________,________,__X_____,X_______,
  X_____X_,________,________,__X_____,X_______,
  X_____X_,________,XXXXXXXX,XXX_____,XXXXX___,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,_______X,________,________,_____X__,
  X_____X_,________,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0048[430] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_____XX,XXXXXXXX,______XX,XXXXXXXX,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,________,XXXXXX__,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,XXXXXX__,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____XX,XXXXXXXX,______XX,XXXXXXXX,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,XXXXX___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0052[430] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,________,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,___XXXXX,XXXXX___,
  _XXXXX__,________,________,___XXXXX,XXXXX___,
  _XXXXX__,________,________,___XXXXX,XXXXX___,
  _XXXXX__,________,________,___XXXXX,XXXXX___,
  _XXXXX__,________,________,___XXXXX,XXXXX___,
  _XXXXX__,________,________,___XXXXX,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXX__,________,XXXXXX__,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,________,_______X,_____X__,
  X_____X_,________,XXXXXX__,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,___XXXXX,_____X__,
  X_____X_,_______X,______X_,__X_____,_____X__,
  X_____X_,________,XXXXXX__,__X_____,_____X__,
  X_____X_,________,________,__X_____,_____X__,
  X_____X_,________,________,__X_____,_____X__,
  X_____X_,________,________,__X_____,_____X__,
  X_____X_,________,XXXXXX__,__X_____,_____X__,
  X_____X_,_______X,______X_,___XXXXX,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____X_,_______X,______X_,_______X,_____X__,
  X_____XX,XXXXXXXX,______XX,XXXXXXXX,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,________,________,_____X__,
  X_______,________,XXXXX___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  X_______,________,X___X___,________,_____X__,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_48_0059[516] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXX__,________,XXXXXXXX,XXX_____,_____XXX,XX______,
  _XXXXXXX,XXX_____,XXXXXXXX,XXX_____,XXXXXXXX,XX______,
  _XXXXXXX,XXX_____,________,________,XXXXXXXX,XX______,
  _XXXXXXX,XXX_____,________,________,XXXXXXXX,XX______,
  _XXXXXXX,XXX_____,________,________,XXXXXXXX,XX______,
  _XXXXXXX,XXX_____,________,________,XXXXXXXX,XX______,
  _XXXXXXX,XXX_____,________,________,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,________,___XXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,________,___XXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,________,___XXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,________,___XXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,________,___XXXXX,XXXXX___,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  X_______,________,________,________,________,__X_____,
  X_______,________,________,________,________,__X_____,
  X_______,________,________,________,________,__X_____,
  X_______,________,________,________,________,__X_____,
  X_______,________,________,________,________,__X_____,
  X_____XX,XXXXXXXX,________,___XXXXX,XXXXX___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____X_,_______X,________,___X____,____X___,__X_____,
  X_____XX,XXX____X,________,___X____,XXXXX___,__X_____,
  X_______,___X___X,________,___X___X,________,__X_____,
  X_______,___X____,XXXXXXXX,XXX____X,________,__X_____,
  X_______,___X____,________,_______X,________,__X_____,
  X_______,___X____,________,_______X,________,__X_____,
  X_______,___X____,________,_______X,________,__X_____,
  X_______,___XXXXX,________,___XXXXX,________,__X_____,
  X_______,________,X_______,__X_____,________,__X_____,
  X_______,________,X_______,__X_____,________,__X_____,
  X_______,________,X_______,__X_____,________,__X_____,
  X_______,________,X_______,__X_____,________,__X_____,
  X_______,________,X_______,__X_____,________,__X_____,
  _XXXXX__,________,X_______,__X_____,_____XXX,XX______,
  _____X__,________,X_______,__X_____,_____X__,________,
  _____X__,________,X_______,__X_____,_____X__,________,
  _____X__,________,X_______,__X_____,_____X__,________,
  _____X__,________,XXXXXXXX,XXX_____,_____X__,________,
  ______XX,XXX_____,________,________,XXXXX___,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,__X_____,________,________,X_______,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_48_CharInfo[7] = {
   {   3,   3,   0,  36,  16, acGUI_FontFont_48_0020 } /* code 0020, SPACE */
  ,{  38,  43,   0,   0,  37, acGUI_FontFont_48_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  38,  43,   0,   0,  37, acGUI_FontFont_48_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  38,  43,   0,   0,  37, acGUI_FontFont_48_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  38,  43,   0,   0,  37, acGUI_FontFont_48_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{  38,  43,   0,   0,  37, acGUI_FontFont_48_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  43,  43,   0,   0,  42, acGUI_FontFont_48_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop7 = {
   0x0059 /* first character */
  ,0x0059 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop6 = {
   0x0052 /* first character */
  ,0x0052 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_48_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop5 = {
   0x0048 /* first character */
  ,0x0048 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_48_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop4 = {
   0x0045 /* first character */
  ,0x0045 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_48_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop3 = {
   0x0043 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  2] /* address of first character */
  ,&GUI_FontFont_48_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop2 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_48_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_48_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_48_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_48_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_48 = {
   GUI_FONTTYPE_PROP_FRM /* type of font    */
  ,48 /* height of font  */
  ,48 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_48_Prop1}
  ,36 /* Baseline */
  ,38 /* Height of lowercase characters */
  ,43 /* Height of capital characters */
};

