/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: NextButton_30x30                                      *
* Dimensions:  30 * 30                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmNextButton_30x30;

static GUI_CONST_STORAGE unsigned char _acNextButton_30x30[] = {
  /* RLE: 008 Pixels @ 000,000 */ 8, 0xFF, 
  /* ABS: 014 Pixels @ 008,000 */ 0, 14, 0xFD, 0xF2, 0xC8, 0x79, 0x3D, 0x16, 0x03, 0x03, 0x16, 0x3D, 0x7A, 0xC7, 0xF1, 0xFE, 
  /* RLE: 015 Pixels @ 022,000 */ 15, 0xFF, 
  /* ABS: 003 Pixels @ 007,001 */ 0, 3, 0xDB, 0x86, 0x25, 
  /* RLE: 010 Pixels @ 010,001 */ 10, 0x00, 
  /* ABS: 003 Pixels @ 020,001 */ 0, 3, 0x25, 0x87, 0xDA, 
  /* RLE: 013 Pixels @ 023,001 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 006,002 */ 0, 2, 0x8E, 0x23, 
  /* RLE: 005 Pixels @ 008,002 */ 5, 0x00, 
  /* ABS: 004 Pixels @ 013,002 */ 0, 4, 0x29, 0x3E, 0x3E, 0x29, 
  /* RLE: 005 Pixels @ 017,002 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 022,002 */ 0, 2, 0x24, 0x96, 
  /* RLE: 010 Pixels @ 024,002 */ 10, 0xFF, 
  /* ABS: 016 Pixels @ 004,003 */ 0, 16, 0xF8, 0x66, 0x02, 0x00, 0x00, 0x00, 0x4C, 0xBB, 0xF9, 0xFC, 0xFC, 0xFC, 0xFB, 0xFB, 0xBD, 0x49, 
  /* RLE: 004 Pixels @ 020,003 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 024,003 */ 1, 0x6B, 
  /* RLE: 008 Pixels @ 025,003 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 003,004 */ 0, 7, 0xF8, 0x66, 0x00, 0x00, 0x03, 0x43, 0xD4, 
  /* RLE: 010 Pixels @ 010,004 */ 10, 0xFF, 
  /* ABS: 007 Pixels @ 020,004 */ 0, 7, 0xD1, 0x40, 0x04, 0x00, 0x00, 0x57, 0xFB, 
  /* RLE: 006 Pixels @ 027,004 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 003,005 */ 0, 5, 0x66, 0x00, 0x00, 0x07, 0x91, 
  /* RLE: 014 Pixels @ 008,005 */ 14, 0xFF, 
  /* ABS: 006 Pixels @ 022,005 */ 0, 6, 0x91, 0x0E, 0x00, 0x00, 0x65, 0xFC, 
  /* RLE: 004 Pixels @ 028,005 */ 4, 0xFF, 
  /* ABS: 005 Pixels @ 002,006 */ 0, 5, 0x8E, 0x02, 0x00, 0x07, 0xB7, 
  /* RLE: 016 Pixels @ 007,006 */ 16, 0xFF, 
  /* ABS: 013 Pixels @ 023,006 */ 0, 13, 0xA9, 0x0A, 0x00, 0x03, 0xA1, 0xFF, 0xFF, 0xFF, 0xDB, 0x23, 0x00, 0x03, 0x91, 
  /* RLE: 006 Pixels @ 006,007 */ 6, 0xFF, 
  /* RLE: 001 Pixels @ 012,007 */ 1, 0xFE, 
  /* RLE: 011 Pixels @ 013,007 */ 11, 0xFF, 
  /* ABS: 011 Pixels @ 024,007 */ 0, 11, 0x83, 0x00, 0x00, 0x23, 0xEA, 0xFF, 0xFD, 0x86, 0x00, 0x00, 0x43, 
  /* RLE: 006 Pixels @ 005,008 */ 6, 0xFF, 
  /* ABS: 003 Pixels @ 011,008 */ 0, 3, 0xE2, 0x8E, 0xBE, 
  /* RLE: 011 Pixels @ 014,008 */ 11, 0xFF, 
  /* ABS: 010 Pixels @ 025,008 */ 0, 10, 0x41, 0x00, 0x00, 0x8E, 0xFF, 0xF2, 0x25, 0x00, 0x00, 0xD4, 
  /* RLE: 006 Pixels @ 005,009 */ 6, 0xFF, 
  /* ABS: 004 Pixels @ 011,009 */ 0, 4, 0x5F, 0x00, 0x0A, 0x8F, 
  /* RLE: 010 Pixels @ 015,009 */ 10, 0xFF, 
  /* ABS: 009 Pixels @ 025,009 */ 0, 9, 0xE3, 0x01, 0x00, 0x0D, 0xFF, 0xC8, 0x00, 0x00, 0x4C, 
  /* RLE: 007 Pixels @ 004,010 */ 7, 0xFF, 
  /* ABS: 005 Pixels @ 011,010 */ 0, 5, 0x84, 0x00, 0x00, 0x04, 0x77, 
  /* RLE: 010 Pixels @ 016,010 */ 10, 0xFF, 
  /* ABS: 008 Pixels @ 026,010 */ 0, 8, 0x63, 0x00, 0x00, 0xAE, 0x79, 0x00, 0x00, 0xBB, 
  /* RLE: 007 Pixels @ 004,011 */ 7, 0xFF, 
  /* ABS: 007 Pixels @ 011,011 */ 0, 7, 0xFC, 0x68, 0x00, 0x00, 0x00, 0x7D, 0xF9, 
  /* RLE: 008 Pixels @ 018,011 */ 8, 0xFF, 
  /* ABS: 008 Pixels @ 026,011 */ 0, 8, 0xBC, 0x00, 0x00, 0x58, 0x3D, 0x00, 0x00, 0xF9, 
  /* RLE: 008 Pixels @ 004,012 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 012,012 */ 0, 7, 0xFB, 0x77, 0x00, 0x00, 0x00, 0x6E, 0xF9, 
  /* RLE: 007 Pixels @ 019,012 */ 7, 0xFF, 
  /* ABS: 008 Pixels @ 026,012 */ 0, 8, 0xD8, 0x1A, 0x00, 0x1B, 0x16, 0x00, 0x29, 0xFC, 
  /* RLE: 009 Pixels @ 004,013 */ 9, 0xFF, 
  /* ABS: 007 Pixels @ 013,013 */ 0, 7, 0xFE, 0x9B, 0x00, 0x00, 0x00, 0x47, 0xF4, 
  /* RLE: 006 Pixels @ 020,013 */ 6, 0xFF, 
  /* ABS: 008 Pixels @ 026,013 */ 0, 8, 0xE7, 0x34, 0x00, 0x07, 0x03, 0x00, 0x3E, 0xFC, 
  /* RLE: 011 Pixels @ 004,014 */ 11, 0xFF, 
  /* ABS: 005 Pixels @ 015,014 */ 0, 5, 0xAD, 0x03, 0x00, 0x00, 0x5F, 
  /* RLE: 006 Pixels @ 020,014 */ 6, 0xFF, 
  /* ABS: 008 Pixels @ 026,014 */ 0, 8, 0xEE, 0x41, 0x00, 0x01, 0x03, 0x00, 0x3E, 0xFC, 
  /* RLE: 011 Pixels @ 004,015 */ 11, 0xFF, 
  /* ABS: 005 Pixels @ 015,015 */ 0, 5, 0xAC, 0x11, 0x00, 0x00, 0x67, 
  /* RLE: 006 Pixels @ 020,015 */ 6, 0xFF, 
  /* ABS: 008 Pixels @ 026,015 */ 0, 8, 0xEE, 0x41, 0x00, 0x01, 0x16, 0x00, 0x29, 0xFB, 
  /* RLE: 010 Pixels @ 004,016 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 014,016 */ 0, 6, 0x87, 0x02, 0x00, 0x00, 0x59, 0xEC, 
  /* RLE: 006 Pixels @ 020,016 */ 6, 0xFF, 
  /* ABS: 008 Pixels @ 026,016 */ 0, 8, 0xE7, 0x34, 0x00, 0x07, 0x3D, 0x00, 0x00, 0xFB, 
  /* RLE: 009 Pixels @ 004,017 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 013,017 */ 0, 6, 0x6A, 0x04, 0x00, 0x00, 0x77, 0xF8, 
  /* RLE: 007 Pixels @ 019,017 */ 7, 0xFF, 
  /* ABS: 008 Pixels @ 026,017 */ 0, 8, 0xD8, 0x1A, 0x00, 0x1A, 0x7A, 0x00, 0x00, 0xBD, 
  /* RLE: 007 Pixels @ 004,018 */ 7, 0xFF, 
  /* ABS: 007 Pixels @ 011,018 */ 0, 7, 0xF7, 0x71, 0x00, 0x00, 0x02, 0x77, 0xFD, 
  /* RLE: 008 Pixels @ 018,018 */ 8, 0xFF, 
  /* ABS: 008 Pixels @ 026,018 */ 0, 8, 0xBC, 0x00, 0x00, 0x57, 0xC7, 0x00, 0x00, 0x49, 
  /* RLE: 007 Pixels @ 004,019 */ 7, 0xFF, 
  /* ABS: 005 Pixels @ 011,019 */ 0, 5, 0x89, 0x00, 0x00, 0x02, 0x7E, 
  /* RLE: 010 Pixels @ 016,019 */ 10, 0xFF, 
  /* ABS: 009 Pixels @ 026,019 */ 0, 9, 0x62, 0x00, 0x00, 0xB1, 0xF1, 0x26, 0x00, 0x00, 0xD1, 
  /* RLE: 006 Pixels @ 005,020 */ 6, 0xFF, 
  /* ABS: 004 Pixels @ 011,020 */ 0, 4, 0x5D, 0x00, 0x00, 0xA3, 
  /* RLE: 010 Pixels @ 015,020 */ 10, 0xFF, 
  /* ABS: 010 Pixels @ 025,020 */ 0, 10, 0xE4, 0x00, 0x00, 0x0F, 0xFF, 0xFE, 0x87, 0x00, 0x00, 0x3F, 
  /* RLE: 006 Pixels @ 005,021 */ 6, 0xFF, 
  /* ABS: 004 Pixels @ 011,021 */ 0, 4, 0xED, 0x86, 0xCD, 0xFE, 
  /* RLE: 010 Pixels @ 015,021 */ 10, 0xFF, 
  /* ABS: 011 Pixels @ 025,021 */ 0, 11, 0x3E, 0x00, 0x00, 0x8B, 0xFF, 0xFF, 0xDA, 0x24, 0x00, 0x04, 0x90, 
  /* RLE: 018 Pixels @ 006,022 */ 18, 0xFF, 
  /* ABS: 013 Pixels @ 024,022 */ 0, 13, 0x8C, 0x00, 0x00, 0x20, 0xEF, 0xFF, 0xFF, 0xFF, 0x96, 0x00, 0x00, 0x0E, 0xA9, 
  /* RLE: 016 Pixels @ 007,023 */ 16, 0xFF, 
  /* ABS: 005 Pixels @ 023,023 */ 0, 5, 0xA7, 0x0A, 0x00, 0x04, 0xA1, 
  /* RLE: 005 Pixels @ 028,023 */ 5, 0xFF, 
  /* ABS: 005 Pixels @ 003,024 */ 0, 5, 0x6B, 0x00, 0x00, 0x0A, 0x82, 
  /* RLE: 014 Pixels @ 008,024 */ 14, 0xFF, 
  /* ABS: 005 Pixels @ 022,024 */ 0, 5, 0x8C, 0x0A, 0x00, 0x00, 0x60, 
  /* RLE: 007 Pixels @ 027,024 */ 7, 0xFF, 
  /* ABS: 006 Pixels @ 004,025 */ 0, 6, 0x58, 0x00, 0x00, 0x00, 0x41, 0xE2, 
  /* RLE: 010 Pixels @ 010,025 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 020,025 */ 0, 6, 0xE4, 0x3E, 0x00, 0x00, 0x00, 0x42, 
  /* RLE: 008 Pixels @ 026,025 */ 8, 0xFF, 
  /* ABS: 021 Pixels @ 004,026 */ 0, 21, 0xFB, 0x65, 0x03, 0x00, 0x00, 0x01, 0x63, 0xBC, 0xD8, 0xE7, 0xEE, 0xEE, 0xE7, 0xD8, 0xBC, 0x62, 0x00, 0x00, 0x00, 0x04, 0x60, 
  /* RLE: 010 Pixels @ 025,026 */ 10, 0xFF, 
  /* ABS: 003 Pixels @ 005,027 */ 0, 3, 0xFC, 0xA1, 0x23, 
  /* RLE: 004 Pixels @ 008,027 */ 4, 0x00, 
  /* ABS: 006 Pixels @ 012,027 */ 0, 6, 0x1A, 0x34, 0x41, 0x41, 0x34, 0x1A, 
  /* RLE: 004 Pixels @ 018,027 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 022,027 */ 0, 2, 0x20, 0xA1, 
  /* RLE: 013 Pixels @ 024,027 */ 13, 0xFF, 
  /* ABS: 003 Pixels @ 007,028 */ 0, 3, 0xEA, 0x8F, 0x0D, 
  /* RLE: 010 Pixels @ 010,028 */ 10, 0x00, 
  /* ABS: 003 Pixels @ 020,028 */ 0, 3, 0x0F, 0x8B, 0xEF, 
  /* RLE: 017 Pixels @ 023,028 */ 17, 0xFF, 
  /* ABS: 010 Pixels @ 010,029 */ 0, 10, 0xAF, 0x57, 0x1B, 0x07, 0x01, 0x01, 0x07, 0x1A, 0x57, 0xB0, 
  /* RLE: 010 Pixels @ 020,029 */ 10, 0xFF, 
  0
};  // 612 bytes for 900 pixels

GUI_CONST_STORAGE GUI_BITMAP bmNextButton_30x30 = {
  30, // xSize
  30, // ySize
  30, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acNextButton_30x30,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
