/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.48                       *
*        Compiled Jun 13 2018, 10:49:54                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Commodore64Angled8.c                                  *
* Font:        Commodore 64 Angled                                   *
* Height:      8                                                     *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  8                                            *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x43 (67)                                     *
* Character enabled:   0x74 (116)                                    *
* Character enabled:   0x6C (108)                                    *
* Character enabled:   0x72 (114)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCommodore64Angled8;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled8_0041[ 18] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x00, 0x77, 0x10,
  0x0A, 0xFF, 0xD1,
  0x4F, 0x85, 0xF7,
  0x4F, 0xBA, 0xF7,
  0x4F, 0x62, 0xF7,
  0x4F, 0x62, 0xF7
};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled8_0043[ 18] = { /* code 0043, LATIN CAPITAL LETTER C */
  0x05, 0x77, 0x70,
  0x3F, 0x97, 0xF7,
  0x4F, 0x60, 0x21,
  0x4F, 0x60, 0x00,
  0x4F, 0x61, 0x95,
  0x1D, 0xDC, 0xE3
};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled8_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  0x47, 0x70,
  0x3B, 0xD0,
  0x09, 0xD0,
  0x09, 0xD0,
  0x09, 0xD0,
  0x6E, 0xF8
};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled8_0072[ 12] = { /* code 0072, LATIN SMALL LETTER R */
  0x3D, 0xCB, 0xC2,
  0x4F, 0x61, 0x95,
  0x4F, 0x60, 0x00,
  0x4F, 0x60, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled8_0074[ 15] = { /* code 0074, LATIN SMALL LETTER T */
  0x00, 0x7A, 0x00,
  0x3B, 0xEF, 0xB6,
  0x00, 0x9D, 0x00,
  0x00, 0x9D, 0x00,
  0x00, 0x6F, 0xB6
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontCommodore64Angled8_CharInfo[5] = {
   {   6,   6,   0,   1,   6, acGUI_FontCommodore64Angled8_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   6,   6,   0,   1,   6, acGUI_FontCommodore64Angled8_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   4,   6,   1,   1,   6, acGUI_FontCommodore64Angled8_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   6,   4,   0,   3,   6, acGUI_FontCommodore64Angled8_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   5,   0,   2,   6, acGUI_FontCommodore64Angled8_0074 } /* code 0074, LATIN SMALL LETTER T */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled8_Prop5 = {
   0x0074 /* first character */
  ,0x0074 /* last character  */
  ,&GUI_FontCommodore64Angled8_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled8_Prop4 = {
   0x0072 /* first character */
  ,0x0072 /* last character  */
  ,&GUI_FontCommodore64Angled8_CharInfo[  3] /* address of first character */
  ,&GUI_FontCommodore64Angled8_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled8_Prop3 = {
   0x006C /* first character */
  ,0x006C /* last character  */
  ,&GUI_FontCommodore64Angled8_CharInfo[  2] /* address of first character */
  ,&GUI_FontCommodore64Angled8_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled8_Prop2 = {
   0x0043 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_FontCommodore64Angled8_CharInfo[  1] /* address of first character */
  ,&GUI_FontCommodore64Angled8_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled8_Prop1 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontCommodore64Angled8_CharInfo[  0] /* address of first character */
  ,&GUI_FontCommodore64Angled8_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCommodore64Angled8 = {
   GUI_FONTTYPE_PROP_AA4_EXT /* type of font    */
  ,8 /* height of font  */
  ,8 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCommodore64Angled8_Prop1}
  ,7 /* Baseline */
  ,4 /* Height of lowercase characters */
  ,6 /* Height of capital characters */
};

