/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.48                       *
*        Compiled Jun 13 2018, 10:49:54                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Commodore64Angled40.c                                 *
* Font:        Commodore 64 Angled                                   *
* Height:      40                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  40                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x53 (83)                                     *
* Character enabled:   0x50 (80)                                     *
* Character enabled:   0x4F (79)                                     *
* Character enabled:   0x52 (82)                                     *
* Character enabled:   0x54 (84)                                     *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x47 (71)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x45 (69)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCommodore64Angled40;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0020[  6] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0041[232] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,________,________,
  ________,XXXXXXXX,________,________,
  _______X,XXXXXXXX,X_______,________,
  ______XX,XXXXXXXX,XX______,________,
  _____XXX,XXXXXXXX,XXX_____,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  ________,________,________,________,
  ________,XXXXXXXX,________,________,
  _______X,________,X_______,________,
  ______X_,________,_X______,________,
  _____X__,________,__X_____,________,
  ____X___,________,___X____,________,
  ___X____,________,____X___,________,
  __X_____,________,_____X__,________,
  _X______,________,______X_,________,
  X_______,________,_______X,________,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  _XXXXXXX,________,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0045[232] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,XXXXXXXX,________,________,
  _XXXXXXX,XXXXXXXX,________,________,
  _XXXXXXX,XXXXXXXX,________,________,
  _XXXXXXX,XXXXXXXX,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,XXXXXXXX,XXXXXXXX,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,XXXXXXXX,________,________,
  X_______,________,X_______,________,
  X_______,________,X_______,________,
  X_______,________,X_______,________,
  X_______,________,X_______,________,
  X_______,XXXXXXXX,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,XXXXXXXX,XXXXXXXX,________,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0047[232] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,____XXXX,XXXXXXXX,________,
  _XXXXXXX,____XXXX,XXXXXXXX,________,
  _XXXXXXX,____XXXX,XXXXXXXX,________,
  _XXXXXXX,____XXXX,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___X____,________,____X___,________,
  __X_____,________,_____X__,________,
  _X______,________,______X_,________,
  X_______,________,_______X,________,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X_______,XXXXXXXX,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X___XXXX,XXXXXXXX,________,
  X_______,X__X____,________,X_______,
  X_______,X__X____,________,X_______,
  X_______,X__X____,________,X_______,
  X_______,X__X____,________,X_______,
  X_______,X___XXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,________,_______X,________,
  _X______,________,______X_,________,
  __X_____,________,_____X__,________,
  ___X____,________,____X___,________,
  ____XXXX,XXXXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_004D[232] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,________,________,
  _XXXX___,________,_______X,XXX_____,
  _XXXXX__,________,______XX,XXX_____,
  _XXXXXX_,________,_____XXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,X_______,___XXXXX,XXX_____,
  _XXXXXXX,XX______,__XXXXXX,XXX_____,
  _XXXXXXX,XXX_____,_XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,_XXXXXXX,XXX_XXXX,XXX_____,
  _XXXXXXX,__XXXXXX,XX__XXXX,XXX_____,
  _XXXXXXX,___XXXXX,X___XXXX,XXX_____,
  _XXXXXXX,____XXXX,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  _XXXXXXX,________,____XXXX,XXX_____,
  ________,________,________,________,
  _XXXX___,________,_______X,XXX_____,
  X____X__,________,______X_,___X____,
  X_____X_,________,_____X__,___X____,
  X______X,________,____X___,___X____,
  X_______,X_______,___X____,___X____,
  X_______,_X______,__X_____,___X____,
  X_______,__X_____,_X______,___X____,
  X_______,___X____,X_______,___X____,
  X_______,____XXXX,________,___X____,
  X_______,________,________,___X____,
  X_______,________,________,___X____,
  X_______,________,________,___X____,
  X_______,________,________,___X____,
  X_______,X_______,___X____,___X____,
  X_______,XX______,__XX____,___X____,
  X_______,X_X_____,_X_X____,___X____,
  X_______,X__X____,X__X____,___X____,
  X_______,X___XXXX,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  X_______,X_______,___X____,___X____,
  _XXXXXXX,________,____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_004F[232] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___X____,________,____X___,________,
  __X_____,________,_____X__,________,
  _X______,________,______X_,________,
  X_______,________,_______X,________,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,________,_______X,________,
  _X______,________,______X_,________,
  __X_____,________,_____X__,________,
  ___X____,________,____X___,________,
  ____XXXX,XXXXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0050[232] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  X_______,________,____X___,________,
  X_______,________,_____X__,________,
  X_______,________,______X_,________,
  X_______,________,_______X,________,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,________,_______X,________,
  X_______,________,______X_,________,
  X_______,________,_____X__,________,
  X_______,________,____X___,________,
  X_______,XXXXXXXX,XXXX____,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  _XXXXXXX,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0052[232] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXXXXX,XXXXXXXX,X_______,________,
  _XXXXXXX,XXXXXXXX,XX______,________,
  _XXXXXXX,XXXXXXXX,XXX_____,________,
  _XXXXXXX,____XXXX,XXXX____,________,
  _XXXXXXX,_____XXX,XXXXX___,________,
  _XXXXXXX,______XX,XXXXXX__,________,
  _XXXXXXX,_______X,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  X_______,________,____X___,________,
  X_______,________,_____X__,________,
  X_______,________,______X_,________,
  X_______,________,_______X,________,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,________,_______X,________,
  X_______,________,______X_,________,
  X_______,________,_____X__,________,
  X_______,________,____X___,________,
  X_______,________,_XXX____,________,
  X_______,________,__X_____,________,
  X_______,________,___X____,________,
  X_______,XXXX____,____X___,________,
  X_______,X___X___,_____X__,________,
  X_______,X____X__,______X_,________,
  X_______,X_____X_,_______X,________,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  _XXXXXXX,________,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0053[232] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  _XXXXXXX,________,________,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,XXXXXXXX,________,
  ________,________,XXXXXXXX,________,
  ________,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,________,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ___X____,________,____X___,________,
  __X_____,________,_____X__,________,
  _X______,________,______X_,________,
  X_______,________,_______X,________,
  X_______,XXXXXXXX,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X_______,XXXXXXXX,________,
  X_______,X_______,________,________,
  X_______,X_______,________,________,
  X_______,XXXXXXXX,XXXXX___,________,
  _X______,________,_____X__,________,
  __X_____,________,______X_,________,
  ___X____,________,_______X,________,
  ____X___,________,________,X_______,
  _____XXX,XXXXXXXX,________,X_______,
  ________,_______X,________,X_______,
  _XXXXXXX,_______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,X______X,________,X_______,
  X_______,XXXXXXXX,________,X_______,
  X_______,________,_______X,________,
  _X______,________,______X_,________,
  __X_____,________,_____X__,________,
  ___X____,________,____X___,________,
  ____XXXX,XXXXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCommodore64Angled40_0054[232] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,XXXXXXXX,________,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  X_______,________,________,X_______,
  _XXXXXXX,________,XXXXXXXX,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  _______X,________,X_______,________,
  ________,XXXXXXXX,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontCommodore64Angled40_CharInfo[10] = {
   {   3,   3,   0,  34,  32, acGUI_FontCommodore64Angled40_0020 } /* code 0020, SPACE */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  28,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  25,  29,   4,   7,  32, acGUI_FontCommodore64Angled40_0054 } /* code 0054, LATIN CAPITAL LETTER T */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop7 = {
   0x0052 /* first character */
  ,0x0054 /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop6 = {
   0x004F /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  5] /* address of first character */
  ,&GUI_FontCommodore64Angled40_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop5 = {
   0x004D /* first character */
  ,0x004D /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  4] /* address of first character */
  ,&GUI_FontCommodore64Angled40_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop4 = {
   0x0047 /* first character */
  ,0x0047 /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  3] /* address of first character */
  ,&GUI_FontCommodore64Angled40_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop3 = {
   0x0045 /* first character */
  ,0x0045 /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  2] /* address of first character */
  ,&GUI_FontCommodore64Angled40_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop2 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  1] /* address of first character */
  ,&GUI_FontCommodore64Angled40_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCommodore64Angled40_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontCommodore64Angled40_CharInfo[  0] /* address of first character */
  ,&GUI_FontCommodore64Angled40_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCommodore64Angled40 = {
   GUI_FONTTYPE_PROP_FRM /* type of font    */
  ,40 /* height of font  */
  ,40 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCommodore64Angled40_Prop1}
  ,34 /* Baseline */
  ,21 /* Height of lowercase characters */
  ,29 /* Height of capital characters */
};

