/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: ExitButton_36x36                                      *
* Dimensions:  36 * 36                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmExitButton_36x36;

static GUI_CONST_STORAGE unsigned char _acExitButton_36x36[] = {
  /* RLE: 013 Pixels @ 000,000 */ 13, 0xFF, 
  /* ABS: 010 Pixels @ 013,000 */ 0, 10, 0xC3, 0x8F, 0x68, 0x4E, 0x42, 0x42, 0x4E, 0x68, 0x8F, 0xC4, 
  /* RLE: 023 Pixels @ 023,000 */ 23, 0xFF, 
  /* ABS: 002 Pixels @ 010,001 */ 0, 2, 0xFD, 0x75, 
  /* RLE: 012 Pixels @ 012,001 */ 12, 0x00, 
  /* RLE: 001 Pixels @ 024,001 */ 1, 0x75, 
  /* RLE: 020 Pixels @ 025,001 */ 20, 0xFF, 
  /* ABS: 018 Pixels @ 009,002 */ 0, 18, 0x4C, 0x07, 0x00, 0x00, 0x00, 0x21, 0x63, 0x8E, 0xA3, 0xA4, 0x8E, 0x63, 0x22, 0x00, 0x00, 0x00, 0x08, 0x4C, 
  /* RLE: 016 Pixels @ 027,002 */ 16, 0xFF, 
  /* ABS: 007 Pixels @ 007,003 */ 0, 7, 0xB4, 0x00, 0x00, 0x00, 0x26, 0x7D, 0xF5, 
  /* RLE: 008 Pixels @ 014,003 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 022,003 */ 0, 7, 0xF8, 0x7E, 0x26, 0x00, 0x00, 0x00, 0xB4, 
  /* RLE: 013 Pixels @ 029,003 */ 13, 0xFF, 
  /* ABS: 005 Pixels @ 006,004 */ 0, 5, 0x66, 0x00, 0x00, 0x00, 0xB6, 
  /* RLE: 014 Pixels @ 011,004 */ 14, 0xFF, 
  /* ABS: 005 Pixels @ 025,004 */ 0, 5, 0xB6, 0x00, 0x00, 0x00, 0x67, 
  /* RLE: 011 Pixels @ 030,004 */ 11, 0xFF, 
  /* ABS: 004 Pixels @ 005,005 */ 0, 4, 0x60, 0x00, 0x00, 0x51, 
  /* RLE: 018 Pixels @ 009,005 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 027,005 */ 0, 4, 0x51, 0x00, 0x00, 0x60, 
  /* RLE: 009 Pixels @ 031,005 */ 9, 0xFF, 
  /* ABS: 004 Pixels @ 004,006 */ 0, 4, 0x68, 0x00, 0x00, 0x7D, 
  /* RLE: 020 Pixels @ 008,006 */ 20, 0xFF, 
  /* ABS: 004 Pixels @ 028,006 */ 0, 4, 0x7D, 0x00, 0x00, 0x69, 
  /* RLE: 007 Pixels @ 032,006 */ 7, 0xFF, 
  /* ABS: 004 Pixels @ 003,007 */ 0, 4, 0xB5, 0x00, 0x00, 0x7D, 
  /* RLE: 022 Pixels @ 007,007 */ 22, 0xFF, 
  /* ABS: 004 Pixels @ 029,007 */ 0, 4, 0x7C, 0x00, 0x00, 0xB6, 
  /* RLE: 006 Pixels @ 033,007 */ 6, 0xFF, 
  /* ABS: 003 Pixels @ 003,008 */ 0, 3, 0x01, 0x00, 0x51, 
  /* RLE: 024 Pixels @ 006,008 */ 24, 0xFF, 
  /* ABS: 003 Pixels @ 030,008 */ 0, 3, 0x50, 0x00, 0x01, 
  /* RLE: 005 Pixels @ 033,008 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 002,009 */ 0, 3, 0x4F, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 005,009 */ 26, 0xFF, 
  /* ABS: 003 Pixels @ 031,009 */ 0, 3, 0x00, 0x00, 0x50, 
  /* RLE: 004 Pixels @ 034,009 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 002,010 */ 0, 3, 0x08, 0x00, 0xB6, 
  /* RLE: 026 Pixels @ 005,010 */ 26, 0xFF, 
  /* ABS: 009 Pixels @ 031,010 */ 0, 9, 0xB6, 0x00, 0x09, 0xFF, 0xFF, 0xFF, 0x7A, 0x00, 0x26, 
  /* RLE: 009 Pixels @ 004,011 */ 9, 0xFF, 
  /* ABS: 002 Pixels @ 013,011 */ 0, 2, 0xB5, 0x93, 
  /* RLE: 006 Pixels @ 015,011 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 021,011 */ 0, 2, 0x93, 0xB5, 
  /* RLE: 009 Pixels @ 023,011 */ 9, 0xFF, 
  /* ABS: 008 Pixels @ 032,011 */ 0, 8, 0x26, 0x00, 0x7B, 0xFF, 0xFF, 0x00, 0x00, 0x7D, 
  /* RLE: 008 Pixels @ 004,012 */ 8, 0xFF, 
  /* ABS: 004 Pixels @ 012,012 */ 0, 4, 0x9E, 0x00, 0x00, 0x7D, 
  /* RLE: 004 Pixels @ 016,012 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 020,012 */ 0, 4, 0x7E, 0x00, 0x00, 0x9F, 
  /* RLE: 008 Pixels @ 024,012 */ 8, 0xFF, 
  /* ABS: 008 Pixels @ 032,012 */ 0, 8, 0x7C, 0x00, 0x01, 0xFF, 0xC7, 0x00, 0x00, 0xF5, 
  /* RLE: 007 Pixels @ 004,013 */ 7, 0xFF, 
  /* ABS: 014 Pixels @ 011,013 */ 0, 14, 0xB5, 0x00, 0x01, 0x01, 0x00, 0x88, 0xFF, 0xFF, 0x88, 0x00, 0x01, 0x01, 0x00, 0xB5, 
  /* RLE: 007 Pixels @ 025,013 */ 7, 0xFF, 
  /* ABS: 007 Pixels @ 032,013 */ 0, 7, 0xF5, 0x00, 0x00, 0xC8, 0x92, 0x00, 0x21, 
  /* RLE: 008 Pixels @ 003,014 */ 8, 0xFF, 
  /* ABS: 014 Pixels @ 011,014 */ 0, 14, 0x92, 0x00, 0x01, 0x00, 0x01, 0x00, 0x8D, 0x8E, 0x00, 0x01, 0x00, 0x01, 0x00, 0x94, 
  /* RLE: 008 Pixels @ 025,014 */ 8, 0xFF, 
  /* ABS: 006 Pixels @ 033,014 */ 0, 6, 0x21, 0x00, 0x93, 0x6B, 0x00, 0x62, 
  /* RLE: 009 Pixels @ 003,015 */ 9, 0xFF, 
  /* ABS: 012 Pixels @ 012,015 */ 0, 12, 0x7D, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x7E, 
  /* RLE: 009 Pixels @ 024,015 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 033,015 */ 0, 6, 0x61, 0x00, 0x6B, 0x51, 0x00, 0x8D, 
  /* RLE: 010 Pixels @ 003,016 */ 10, 0xFF, 
  /* ABS: 003 Pixels @ 013,016 */ 0, 3, 0x88, 0x00, 0x01, 
  /* RLE: 004 Pixels @ 016,016 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 020,016 */ 0, 3, 0x01, 0x00, 0x88, 
  /* RLE: 010 Pixels @ 023,016 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 033,016 */ 0, 6, 0x8D, 0x00, 0x52, 0x44, 0x00, 0xA3, 
  /* RLE: 011 Pixels @ 003,017 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 014,017 */ 1, 0x8D, 
  /* RLE: 006 Pixels @ 015,017 */ 6, 0x00, 
  /* RLE: 001 Pixels @ 021,017 */ 1, 0x8E, 
  /* RLE: 011 Pixels @ 022,017 */ 11, 0xFF, 
  /* ABS: 006 Pixels @ 033,017 */ 0, 6, 0xA2, 0x00, 0x45, 0x45, 0x00, 0xA2, 
  /* RLE: 011 Pixels @ 003,018 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 014,018 */ 1, 0x8D, 
  /* RLE: 006 Pixels @ 015,018 */ 6, 0x00, 
  /* RLE: 001 Pixels @ 021,018 */ 1, 0x8D, 
  /* RLE: 011 Pixels @ 022,018 */ 11, 0xFF, 
  /* ABS: 006 Pixels @ 033,018 */ 0, 6, 0xA2, 0x00, 0x45, 0x51, 0x00, 0x8D, 
  /* RLE: 010 Pixels @ 003,019 */ 10, 0xFF, 
  /* ABS: 003 Pixels @ 013,019 */ 0, 3, 0x87, 0x00, 0x01, 
  /* RLE: 004 Pixels @ 016,019 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 020,019 */ 0, 3, 0x01, 0x00, 0x88, 
  /* RLE: 010 Pixels @ 023,019 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 033,019 */ 0, 6, 0x8D, 0x00, 0x51, 0x6B, 0x00, 0x62, 
  /* RLE: 009 Pixels @ 003,020 */ 9, 0xFF, 
  /* ABS: 012 Pixels @ 012,020 */ 0, 12, 0x7D, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x7E, 
  /* RLE: 009 Pixels @ 024,020 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 033,020 */ 0, 6, 0x61, 0x00, 0x6C, 0x92, 0x00, 0x21, 
  /* RLE: 008 Pixels @ 003,021 */ 8, 0xFF, 
  /* ABS: 014 Pixels @ 011,021 */ 0, 14, 0x93, 0x00, 0x01, 0x00, 0x01, 0x00, 0x8E, 0x8D, 0x00, 0x01, 0x00, 0x01, 0x00, 0x93, 
  /* RLE: 008 Pixels @ 025,021 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 033,021 */ 0, 7, 0x21, 0x00, 0x93, 0xC7, 0x00, 0x00, 0xF5, 
  /* RLE: 007 Pixels @ 004,022 */ 7, 0xFF, 
  /* ABS: 014 Pixels @ 011,022 */ 0, 14, 0xB5, 0x00, 0x01, 0x01, 0x00, 0x88, 0xFF, 0xFF, 0x87, 0x00, 0x01, 0x01, 0x00, 0xB5, 
  /* RLE: 007 Pixels @ 025,022 */ 7, 0xFF, 
  /* ABS: 008 Pixels @ 032,022 */ 0, 8, 0xF2, 0x00, 0x00, 0xC8, 0xFF, 0x01, 0x00, 0x7D, 
  /* RLE: 008 Pixels @ 004,023 */ 8, 0xFF, 
  /* ABS: 004 Pixels @ 012,023 */ 0, 4, 0x9E, 0x00, 0x00, 0x7E, 
  /* RLE: 004 Pixels @ 016,023 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 020,023 */ 0, 4, 0x7D, 0x00, 0x00, 0x9F, 
  /* RLE: 008 Pixels @ 024,023 */ 8, 0xFF, 
  /* ABS: 008 Pixels @ 032,023 */ 0, 8, 0x7C, 0x00, 0x01, 0xFF, 0xFF, 0x7A, 0x00, 0x26, 
  /* RLE: 009 Pixels @ 004,024 */ 9, 0xFF, 
  /* ABS: 002 Pixels @ 013,024 */ 0, 2, 0xB5, 0x93, 
  /* RLE: 006 Pixels @ 015,024 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 021,024 */ 0, 2, 0x92, 0xB5, 
  /* RLE: 009 Pixels @ 023,024 */ 9, 0xFF, 
  /* ABS: 009 Pixels @ 032,024 */ 0, 9, 0x25, 0x00, 0x7B, 0xFF, 0xFF, 0xFF, 0x09, 0x00, 0xB6, 
  /* RLE: 026 Pixels @ 005,025 */ 26, 0xFF, 
  /* ABS: 003 Pixels @ 031,025 */ 0, 3, 0xB5, 0x00, 0x09, 
  /* RLE: 004 Pixels @ 034,025 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 002,026 */ 0, 3, 0x4E, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 005,026 */ 26, 0xFF, 
  /* ABS: 003 Pixels @ 031,026 */ 0, 3, 0x00, 0x00, 0x50, 
  /* RLE: 005 Pixels @ 034,026 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 003,027 */ 0, 3, 0x01, 0x00, 0x51, 
  /* RLE: 024 Pixels @ 006,027 */ 24, 0xFF, 
  /* ABS: 003 Pixels @ 030,027 */ 0, 3, 0x50, 0x00, 0x01, 
  /* RLE: 006 Pixels @ 033,027 */ 6, 0xFF, 
  /* ABS: 004 Pixels @ 003,028 */ 0, 4, 0xB5, 0x00, 0x00, 0x7D, 
  /* RLE: 022 Pixels @ 007,028 */ 22, 0xFF, 
  /* ABS: 004 Pixels @ 029,028 */ 0, 4, 0x7D, 0x00, 0x00, 0xB6, 
  /* RLE: 007 Pixels @ 033,028 */ 7, 0xFF, 
  /* ABS: 004 Pixels @ 004,029 */ 0, 4, 0x68, 0x00, 0x00, 0x7E, 
  /* RLE: 020 Pixels @ 008,029 */ 20, 0xFF, 
  /* ABS: 004 Pixels @ 028,029 */ 0, 4, 0x7D, 0x00, 0x00, 0x6A, 
  /* RLE: 009 Pixels @ 032,029 */ 9, 0xFF, 
  /* ABS: 004 Pixels @ 005,030 */ 0, 4, 0x5F, 0x00, 0x00, 0x51, 
  /* RLE: 018 Pixels @ 009,030 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 027,030 */ 0, 4, 0x51, 0x00, 0x00, 0x61, 
  /* RLE: 011 Pixels @ 031,030 */ 11, 0xFF, 
  /* ABS: 005 Pixels @ 006,031 */ 0, 5, 0x66, 0x00, 0x00, 0x00, 0xB7, 
  /* RLE: 014 Pixels @ 011,031 */ 14, 0xFF, 
  /* ABS: 005 Pixels @ 025,031 */ 0, 5, 0xB6, 0x00, 0x00, 0x00, 0x68, 
  /* RLE: 013 Pixels @ 030,031 */ 13, 0xFF, 
  /* ABS: 007 Pixels @ 007,032 */ 0, 7, 0xB4, 0x00, 0x00, 0x00, 0x26, 0x7D, 0xF8, 
  /* RLE: 008 Pixels @ 014,032 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 022,032 */ 0, 7, 0xF5, 0x7D, 0x26, 0x00, 0x00, 0x00, 0xB5, 
  /* RLE: 016 Pixels @ 029,032 */ 16, 0xFF, 
  /* ABS: 018 Pixels @ 009,033 */ 0, 18, 0x4C, 0x08, 0x00, 0x00, 0x00, 0x21, 0x63, 0x8E, 0xA3, 0xA3, 0x8D, 0x62, 0x21, 0x00, 0x00, 0x00, 0x08, 0x4C, 
  /* RLE: 020 Pixels @ 027,033 */ 20, 0xFF, 
  /* RLE: 001 Pixels @ 011,034 */ 1, 0x75, 
  /* RLE: 012 Pixels @ 012,034 */ 12, 0x00, 
  /* RLE: 001 Pixels @ 024,034 */ 1, 0x76, 
  /* RLE: 024 Pixels @ 025,034 */ 24, 0xFF, 
  /* ABS: 010 Pixels @ 013,035 */ 0, 10, 0xC4, 0x8F, 0x69, 0x4F, 0x42, 0x42, 0x4F, 0x69, 0x8F, 0xC4, 
  /* RLE: 013 Pixels @ 023,035 */ 13, 0xFF, 
  0
};  // 708 bytes for 1296 pixels

GUI_CONST_STORAGE GUI_BITMAP bmExitButton_36x36 = {
  36, // xSize
  36, // ySize
  36, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acExitButton_36x36,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
