/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelpButton_36x36                                      *
* Dimensions:  36 * 36                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmHelpButton_36x36;

static GUI_CONST_STORAGE unsigned char _acHelpButton_36x36[] = {
  /* RLE: 013 Pixels @ 000,000 */ 13, 0xFF, 
  /* ABS: 010 Pixels @ 013,000 */ 0, 10, 0xC1, 0x8A, 0x68, 0x4C, 0x40, 0x42, 0x4C, 0x66, 0x8F, 0xC1, 
  /* RLE: 023 Pixels @ 023,000 */ 23, 0xFF, 
  /* ABS: 002 Pixels @ 010,001 */ 0, 2, 0xF9, 0x74, 
  /* RLE: 012 Pixels @ 012,001 */ 12, 0x00, 
  /* ABS: 002 Pixels @ 024,001 */ 0, 2, 0x73, 0xF9, 
  /* RLE: 019 Pixels @ 026,001 */ 19, 0xFF, 
  /* ABS: 018 Pixels @ 009,002 */ 0, 18, 0x49, 0x08, 0x00, 0x00, 0x00, 0x22, 0x62, 0x8A, 0xA2, 0x9F, 0x8B, 0x62, 0x21, 0x00, 0x00, 0x00, 0x08, 0x4C, 
  /* RLE: 016 Pixels @ 027,002 */ 16, 0xFF, 
  /* ABS: 006 Pixels @ 007,003 */ 0, 6, 0xB2, 0x00, 0x00, 0x00, 0x26, 0x79, 
  /* RLE: 009 Pixels @ 013,003 */ 9, 0xFF, 
  /* ABS: 007 Pixels @ 022,003 */ 0, 7, 0xFD, 0x7B, 0x25, 0x00, 0x00, 0x02, 0xB2, 
  /* RLE: 013 Pixels @ 029,003 */ 13, 0xFF, 
  /* ABS: 005 Pixels @ 006,004 */ 0, 5, 0x65, 0x00, 0x00, 0x00, 0xB5, 
  /* RLE: 014 Pixels @ 011,004 */ 14, 0xFF, 
  /* ABS: 005 Pixels @ 025,004 */ 0, 5, 0xB4, 0x00, 0x00, 0x00, 0x68, 
  /* RLE: 011 Pixels @ 030,004 */ 11, 0xFF, 
  /* ABS: 004 Pixels @ 005,005 */ 0, 4, 0x5E, 0x00, 0x00, 0x51, 
  /* RLE: 018 Pixels @ 009,005 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 027,005 */ 0, 4, 0x4F, 0x00, 0x00, 0x60, 
  /* RLE: 009 Pixels @ 031,005 */ 9, 0xFF, 
  /* ABS: 004 Pixels @ 004,006 */ 0, 4, 0x66, 0x00, 0x00, 0x7E, 
  /* RLE: 020 Pixels @ 008,006 */ 20, 0xFF, 
  /* ABS: 004 Pixels @ 028,006 */ 0, 4, 0x79, 0x00, 0x00, 0x67, 
  /* RLE: 007 Pixels @ 032,006 */ 7, 0xFF, 
  /* ABS: 004 Pixels @ 003,007 */ 0, 4, 0xB4, 0x00, 0x00, 0x7E, 
  /* RLE: 022 Pixels @ 007,007 */ 22, 0xFF, 
  /* ABS: 004 Pixels @ 029,007 */ 0, 4, 0x7A, 0x00, 0x00, 0xB3, 
  /* RLE: 006 Pixels @ 033,007 */ 6, 0xFF, 
  /* ABS: 003 Pixels @ 003,008 */ 0, 3, 0x00, 0x00, 0x51, 
  /* RLE: 024 Pixels @ 006,008 */ 24, 0xFF, 
  /* ABS: 003 Pixels @ 030,008 */ 0, 3, 0x4E, 0x00, 0x01, 
  /* RLE: 005 Pixels @ 033,008 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 002,009 */ 0, 3, 0x4B, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 005,009 */ 26, 0xFF, 
  /* ABS: 010 Pixels @ 031,009 */ 0, 10, 0x00, 0x00, 0x4D, 0xFF, 0xFF, 0xFF, 0xFC, 0x08, 0x00, 0xB6, 
  /* RLE: 010 Pixels @ 005,010 */ 10, 0xFF, 
  /* ABS: 007 Pixels @ 015,010 */ 0, 7, 0xB4, 0x71, 0x49, 0x40, 0x4F, 0x75, 0xBE, 
  /* RLE: 009 Pixels @ 022,010 */ 9, 0xFF, 
  /* ABS: 009 Pixels @ 031,010 */ 0, 9, 0xB3, 0x00, 0x08, 0xFF, 0xFF, 0xFF, 0x78, 0x00, 0x27, 
  /* RLE: 009 Pixels @ 004,011 */ 9, 0xFF, 
  /* ABS: 005 Pixels @ 013,011 */ 0, 5, 0xE5, 0x1D, 0x00, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 018,011 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 022,011 */ 1, 0x66, 
  /* RLE: 009 Pixels @ 023,011 */ 9, 0xFF, 
  /* ABS: 008 Pixels @ 032,011 */ 0, 8, 0x25, 0x00, 0x74, 0xFF, 0xFF, 0x00, 0x00, 0x7A, 
  /* RLE: 008 Pixels @ 004,012 */ 8, 0xFF, 
  /* ABS: 004 Pixels @ 012,012 */ 0, 4, 0xAF, 0x09, 0x00, 0x01, 
  /* RLE: 004 Pixels @ 016,012 */ 4, 0x00, 
  /* ABS: 004 Pixels @ 020,012 */ 0, 4, 0x01, 0x00, 0x00, 0x6D, 
  /* RLE: 008 Pixels @ 024,012 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 032,012 */ 0, 7, 0x79, 0x00, 0x00, 0xFF, 0xC4, 0x00, 0x00, 
  /* RLE: 009 Pixels @ 003,013 */ 9, 0xFF, 
  /* ABS: 012 Pixels @ 012,013 */ 0, 12, 0xE5, 0x0D, 0x00, 0x03, 0x3A, 0x8D, 0xA3, 0x81, 0x21, 0x00, 0x01, 0x1F, 
  /* RLE: 008 Pixels @ 024,013 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 032,013 */ 0, 7, 0xE6, 0x00, 0x00, 0xC1, 0x8C, 0x00, 0x23, 
  /* RLE: 010 Pixels @ 003,014 */ 10, 0xFF, 
  /* ABS: 003 Pixels @ 013,014 */ 0, 3, 0xD3, 0x00, 0xC2, 
  /* RLE: 004 Pixels @ 016,014 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 020,014 */ 0, 4, 0xD6, 0x00, 0x00, 0x0D, 
  /* RLE: 009 Pixels @ 024,014 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 033,014 */ 0, 6, 0x1E, 0x00, 0x8E, 0x6A, 0x00, 0x63, 
  /* RLE: 011 Pixels @ 003,015 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 014,015 */ 1, 0xE5, 
  /* RLE: 005 Pixels @ 015,015 */ 5, 0xFF, 
  /* ABS: 004 Pixels @ 020,015 */ 0, 4, 0xD7, 0x00, 0x00, 0x11, 
  /* RLE: 009 Pixels @ 024,015 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 033,015 */ 0, 6, 0x5F, 0x00, 0x68, 0x4E, 0x00, 0x8C, 
  /* RLE: 016 Pixels @ 003,016 */ 16, 0xFF, 
  /* ABS: 005 Pixels @ 019,016 */ 0, 5, 0xD0, 0x16, 0x01, 0x00, 0x31, 
  /* RLE: 009 Pixels @ 024,016 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 033,016 */ 0, 6, 0x8B, 0x00, 0x4D, 0x42, 0x00, 0xA4, 
  /* RLE: 015 Pixels @ 003,017 */ 15, 0xFF, 
  /* RLE: 001 Pixels @ 018,017 */ 1, 0x37, 
  /* RLE: 004 Pixels @ 019,017 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 023,017 */ 1, 0xCB, 
  /* RLE: 009 Pixels @ 024,017 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 033,017 */ 0, 6, 0x9D, 0x00, 0x42, 0x44, 0x00, 0x9F, 
  /* RLE: 014 Pixels @ 003,018 */ 14, 0xFF, 
  /* ABS: 006 Pixels @ 017,018 */ 0, 6, 0x46, 0x00, 0x00, 0x00, 0x37, 0xD5, 
  /* RLE: 010 Pixels @ 023,018 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 033,018 */ 0, 6, 0x9F, 0x00, 0x43, 0x4E, 0x00, 0x8C, 
  /* RLE: 014 Pixels @ 003,019 */ 14, 0xFF, 
  /* ABS: 004 Pixels @ 017,019 */ 0, 4, 0x15, 0x00, 0x00, 0xC7, 
  /* RLE: 012 Pixels @ 021,019 */ 12, 0xFF, 
  /* ABS: 006 Pixels @ 033,019 */ 0, 6, 0x8B, 0x00, 0x4D, 0x68, 0x00, 0x63, 
  /* RLE: 014 Pixels @ 003,020 */ 14, 0xFF, 
  /* ABS: 003 Pixels @ 017,020 */ 0, 3, 0x00, 0x00, 0xC9, 
  /* RLE: 013 Pixels @ 020,020 */ 13, 0xFF, 
  /* ABS: 006 Pixels @ 033,020 */ 0, 6, 0x5E, 0x00, 0x69, 0x91, 0x00, 0x21, 
  /* RLE: 014 Pixels @ 003,021 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 017,021 */ 0, 2, 0xB7, 0xB5, 
  /* RLE: 014 Pixels @ 019,021 */ 14, 0xFF, 
  /* ABS: 006 Pixels @ 033,021 */ 0, 6, 0x1F, 0x00, 0x8D, 0xC3, 0x00, 0x00, 
  /* RLE: 029 Pixels @ 003,022 */ 29, 0xFF, 
  /* ABS: 008 Pixels @ 032,022 */ 0, 8, 0xE6, 0x00, 0x00, 0xC1, 0xFF, 0x01, 0x00, 0x7C, 
  /* RLE: 013 Pixels @ 004,023 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 017,023 */ 0, 2, 0xB9, 0xB9, 
  /* RLE: 013 Pixels @ 019,023 */ 13, 0xFF, 
  /* ABS: 008 Pixels @ 032,023 */ 0, 8, 0x78, 0x00, 0x00, 0xFF, 0xFF, 0x76, 0x00, 0x25, 
  /* RLE: 012 Pixels @ 004,024 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 016,024 */ 0, 4, 0x8D, 0x00, 0x00, 0x8E, 
  /* RLE: 012 Pixels @ 020,024 */ 12, 0xFF, 
  /* ABS: 009 Pixels @ 032,024 */ 0, 9, 0x25, 0x00, 0x79, 0xFF, 0xFF, 0xFC, 0x08, 0x00, 0xB5, 
  /* RLE: 011 Pixels @ 005,025 */ 11, 0xFF, 
  /* ABS: 004 Pixels @ 016,025 */ 0, 4, 0x56, 0x00, 0x00, 0x5C, 
  /* RLE: 011 Pixels @ 020,025 */ 11, 0xFF, 
  /* ABS: 010 Pixels @ 031,025 */ 0, 10, 0xAF, 0x00, 0x08, 0xF9, 0xFF, 0xFF, 0xFF, 0x4D, 0x00, 0x00, 
  /* RLE: 012 Pixels @ 005,026 */ 12, 0xFF, 
  /* ABS: 002 Pixels @ 017,026 */ 0, 2, 0x1C, 0x1C, 
  /* RLE: 012 Pixels @ 019,026 */ 12, 0xFF, 
  /* ABS: 003 Pixels @ 031,026 */ 0, 3, 0x00, 0x00, 0x4D, 
  /* RLE: 005 Pixels @ 034,026 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 003,027 */ 0, 3, 0x02, 0x00, 0x50, 
  /* RLE: 024 Pixels @ 006,027 */ 24, 0xFF, 
  /* ABS: 003 Pixels @ 030,027 */ 0, 3, 0x4E, 0x00, 0x02, 
  /* RLE: 006 Pixels @ 033,027 */ 6, 0xFF, 
  /* ABS: 004 Pixels @ 003,028 */ 0, 4, 0xB2, 0x00, 0x00, 0x7B, 
  /* RLE: 022 Pixels @ 007,028 */ 22, 0xFF, 
  /* ABS: 004 Pixels @ 029,028 */ 0, 4, 0x7A, 0x00, 0x00, 0xB4, 
  /* RLE: 007 Pixels @ 033,028 */ 7, 0xFF, 
  /* ABS: 004 Pixels @ 004,029 */ 0, 4, 0x67, 0x00, 0x00, 0x7D, 
  /* RLE: 020 Pixels @ 008,029 */ 20, 0xFF, 
  /* ABS: 004 Pixels @ 028,029 */ 0, 4, 0x7C, 0x00, 0x00, 0x6A, 
  /* RLE: 009 Pixels @ 032,029 */ 9, 0xFF, 
  /* ABS: 004 Pixels @ 005,030 */ 0, 4, 0x5F, 0x00, 0x00, 0x51, 
  /* RLE: 018 Pixels @ 009,030 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 027,030 */ 0, 4, 0x50, 0x00, 0x00, 0x5F, 
  /* RLE: 011 Pixels @ 031,030 */ 11, 0xFF, 
  /* ABS: 005 Pixels @ 006,031 */ 0, 5, 0x64, 0x00, 0x00, 0x00, 0xB6, 
  /* RLE: 014 Pixels @ 011,031 */ 14, 0xFF, 
  /* ABS: 005 Pixels @ 025,031 */ 0, 5, 0xB1, 0x00, 0x00, 0x00, 0x69, 
  /* RLE: 013 Pixels @ 030,031 */ 13, 0xFF, 
  /* ABS: 007 Pixels @ 007,032 */ 0, 7, 0xB1, 0x00, 0x00, 0x00, 0x26, 0x7C, 0xE8, 
  /* RLE: 008 Pixels @ 014,032 */ 8, 0xFF, 
  /* ABS: 007 Pixels @ 022,032 */ 0, 7, 0xE7, 0x7B, 0x25, 0x00, 0x00, 0x01, 0xB4, 
  /* RLE: 016 Pixels @ 029,032 */ 16, 0xFF, 
  /* ABS: 018 Pixels @ 009,033 */ 0, 18, 0x4C, 0x07, 0x00, 0x00, 0x00, 0x20, 0x61, 0x8E, 0x9F, 0xA2, 0x8D, 0x60, 0x22, 0x00, 0x00, 0x00, 0x07, 0x4D, 
  /* RLE: 019 Pixels @ 027,033 */ 19, 0xFF, 
  /* ABS: 002 Pixels @ 010,034 */ 0, 2, 0xFE, 0x72, 
  /* RLE: 012 Pixels @ 012,034 */ 12, 0x00, 
  /* ABS: 002 Pixels @ 024,034 */ 0, 2, 0x78, 0xF9, 
  /* RLE: 023 Pixels @ 026,034 */ 23, 0xFF, 
  /* ABS: 010 Pixels @ 013,035 */ 0, 10, 0xC0, 0x8D, 0x68, 0x4C, 0x41, 0x42, 0x4C, 0x68, 0x8D, 0xC1, 
  /* RLE: 013 Pixels @ 023,035 */ 13, 0xFF, 
  0
};  // 666 bytes for 1296 pixels

GUI_CONST_STORAGE GUI_BITMAP bmHelpButton_36x36 = {
  36, // xSize
  36, // ySize
  36, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acHelpButton_36x36,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
