/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: PointingArrow_15x22                                   *
* Dimensions:  15 * 22                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmPointingArrow_15x22;

static GUI_CONST_STORAGE unsigned char _acPointingArrow_15x22[] = {
  /* RLE: 009 Pixels @ 000,000 */ 9, 0xFF, 
  /* ABS: 003 Pixels @ 009,000 */ 0, 3, 0xF5, 0x53, 0xD6, 
  /* RLE: 011 Pixels @ 012,000 */ 11, 0xFF, 
  /* ABS: 005 Pixels @ 008,001 */ 0, 5, 0xED, 0x3F, 0x00, 0x1E, 0xD4, 
  /* RLE: 010 Pixels @ 013,001 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 008,002 */ 0, 6, 0x42, 0x00, 0x00, 0x00, 0x14, 0xD3, 
  /* RLE: 007 Pixels @ 014,002 */ 7, 0xFF, 
  /* ABS: 002 Pixels @ 006,003 */ 0, 2, 0xF7, 0x3C, 
  /* RLE: 005 Pixels @ 008,003 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 013,003 */ 0, 2, 0x27, 0xDE, 
  /* RLE: 005 Pixels @ 000,004 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 005,004 */ 0, 2, 0xF9, 0x4B, 
  /* RLE: 007 Pixels @ 007,004 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 014,004 */ 1, 0x5A, 
  /* RLE: 005 Pixels @ 000,005 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 005,005 */ 1, 0x63, 
  /* RLE: 007 Pixels @ 006,005 */ 7, 0x00, 
  /* ABS: 007 Pixels @ 013,005 */ 0, 7, 0x18, 0xDD, 0xFF, 0xFF, 0xFF, 0xF8, 0x65, 
  /* RLE: 007 Pixels @ 005,006 */ 7, 0x00, 
  /* ABS: 007 Pixels @ 012,006 */ 0, 7, 0x15, 0xBD, 0xFF, 0xFF, 0xFE, 0xFF, 0x5A, 
  /* RLE: 007 Pixels @ 004,007 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 011,007 */ 0, 2, 0x13, 0xCB, 
  /* RLE: 004 Pixels @ 013,007 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 002,008 */ 1, 0x5D, 
  /* RLE: 007 Pixels @ 003,008 */ 7, 0x00, 
  /* ABS: 007 Pixels @ 010,008 */ 0, 7, 0x10, 0xC5, 0xFF, 0xFF, 0xFF, 0xFC, 0x75, 
  /* RLE: 007 Pixels @ 002,009 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 009,009 */ 0, 2, 0x0C, 0xB3, 
  /* RLE: 004 Pixels @ 011,009 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 000,010 */ 1, 0x8D, 
  /* RLE: 007 Pixels @ 001,010 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 008,010 */ 0, 2, 0x0A, 0xBA, 
  /* RLE: 005 Pixels @ 010,010 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 000,011 */ 1, 0x77, 
  /* RLE: 007 Pixels @ 001,011 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 008,011 */ 0, 2, 0x10, 0xBC, 
  /* RLE: 005 Pixels @ 010,011 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 000,012 */ 0, 2, 0xFE, 0x73, 
  /* RLE: 007 Pixels @ 002,012 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 009,012 */ 0, 2, 0x0C, 0xAC, 
  /* RLE: 006 Pixels @ 011,012 */ 6, 0xFF, 
  /* RLE: 001 Pixels @ 002,013 */ 1, 0x5F, 
  /* RLE: 007 Pixels @ 003,013 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 010,013 */ 0, 2, 0x0C, 0xC5, 
  /* RLE: 004 Pixels @ 012,013 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 001,014 */ 0, 3, 0xFE, 0xFF, 0x54, 
  /* RLE: 007 Pixels @ 004,014 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 011,014 */ 0, 2, 0x08, 0xD5, 
  /* RLE: 005 Pixels @ 013,014 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 003,015 */ 0, 2, 0xF8, 0x5A, 
  /* RLE: 007 Pixels @ 005,015 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 012,015 */ 0, 2, 0x11, 0xC1, 
  /* RLE: 006 Pixels @ 014,015 */ 6, 0xFF, 
  /* RLE: 001 Pixels @ 005,016 */ 1, 0x5C, 
  /* RLE: 007 Pixels @ 006,016 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 013,016 */ 0, 2, 0x19, 0xDA, 
  /* RLE: 005 Pixels @ 000,017 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 005,017 */ 0, 2, 0xF8, 0x4D, 
  /* RLE: 007 Pixels @ 007,017 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 014,017 */ 1, 0x5E, 
  /* RLE: 006 Pixels @ 000,018 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 006,018 */ 0, 2, 0xF8, 0x3A, 
  /* RLE: 005 Pixels @ 008,018 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 013,018 */ 0, 2, 0x27, 0xE2, 
  /* RLE: 008 Pixels @ 000,019 */ 8, 0xFF, 
  /* ABS: 006 Pixels @ 008,019 */ 0, 6, 0x3A, 0x00, 0x00, 0x00, 0x15, 0xCF, 
  /* RLE: 009 Pixels @ 014,019 */ 9, 0xFF, 
  /* ABS: 005 Pixels @ 008,020 */ 0, 5, 0xED, 0x3C, 0x00, 0x1E, 0xC9, 
  /* RLE: 011 Pixels @ 013,020 */ 11, 0xFF, 
  /* ABS: 006 Pixels @ 009,021 */ 0, 6, 0xEE, 0x59, 0xD1, 0xFF, 0xFF, 0xFF, 
  0
};  // 229 bytes for 330 pixels

GUI_CONST_STORAGE GUI_BITMAP bmPointingArrow_15x22 = {
  15, // xSize
  22, // ySize
  15, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acPointingArrow_15x22,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
