/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Weight_big_6x50                                       *
* Dimensions:  6 * 50                                                *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmWeight_big_6x50;

static GUI_CONST_STORAGE unsigned char _acWeight_big_6x50[] = {
  /* ABS: 007 Pixels @ 000,000 */ 0, 7, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 001,001 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 005,001 */ 1, 0xFF, 
  /* RLE: 276 Pixels @ 000,002 */ 254, 0x00, 22, 0x00, 
  /* RLE: 001 Pixels @ 000,048 */ 1, 0xFF, 
  /* RLE: 004 Pixels @ 001,048 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 005,048 */ 3, 0xFF, 
  /* ABS: 004 Pixels @ 002,049 */ 0, 4, 0x00, 0x00, 0xFF, 0xFF, 
  0
};  // 29 bytes for 300 pixels

GUI_CONST_STORAGE GUI_BITMAP bmWeight_big_6x50 = {
  6, // xSize
  50, // ySize
  6, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acWeight_big_6x50,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
